const helpObj=[
    { // HTML 그룹ID 이름 - localhost:4000/
        Router: "라우터이름",
        Link: "페이지 링크",
        ObjectSort: "HTML 코드 종류",
        ObjectGroup: "HTML 그룹ID 이름",
        ObjectTitle: "객체 타이틀",
        ObjectDescription: "객체 설명",
    },
    { // navTop - localhost:4000/settings
        Router: "Global",
        Link: "/settings",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "셋팅 버튼",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/search
        Router: "Global",
        Link: "/search",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "검색 버튼",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/folio/upload
        Router: "Folio",
        Link: "/folio/upload",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "포트폴리오 업로드",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/folio/:id
        Router: "Folio",
        Link: "/folio/:id",
        ObjectSort: "button",
        ObjectGroup: "navTop",
        ObjectTitle: "포트폴리오 이미지 업로드",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/user/profile/:id
        Router: "User",
        Link: "/user/profile/:id",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "본인 프로필 열람",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/user/logout
        Router: "User",
        Link: "/user/logout",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "로그아웃",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/user/login
        Router: "User",
        Link: "/user/login",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "로그인",
        ObjectDescription: "",
    },
    { // navTop - localhost:4000/user/join
        Router: "User",
        Link: "/user/join",
        ObjectSort: "a",
        ObjectGroup: "navTop",
        ObjectTitle: "회원가입",
        ObjectDescription: "",
    },

    
]